export const tempMusicData = [
  {
    id: 1,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    genre: "Rock",
    isChecked: false,
  },
  {
    id: 2,
    title: "Imagine",
    artist: "John Lennon",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 3,
    title: "Billie Jean",
    artist: "Michael Jackson",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 4,
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    genre: "Grunge",
    isChecked: false,
  },
  {
    id: 5,
    title: "Like a Rolling Stone",
    artist: "Bob Dylan",
    genre: "Folk Rock",
    isChecked: false,
  },
  {
    id: 6,
    title: "Hey Jude",
    artist: "The Beatles",
    genre: "Pop Rock",
    isChecked: false,
  },
  {
    id: 7,
    title: "Respect",
    artist: "Aretha Franklin",
    genre: "Soul",
    isChecked: false,
  },
  {
    id: 8,
    title: "Hotel California",
    artist: "Eagles",
    genre: "Rock",
    isChecked: false,
  },
  {
    id: 9,
    title: "Purple Rain",
    artist: "Prince",
    genre: "Pop Rock",
    isChecked: false,
  },
  {
    id: 10,
    title: "Yesterday",
    artist: "The Beatles",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 11,
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    genre: "Hard Rock",
    isChecked: false,
  },
  {
    id: 12,
    title: "Stairway to Heaven",
    artist: "Led Zeppelin",
    genre: "Rock",
    isChecked: false,
  },
  {
    id: 13,
    title: "I Will Survive",
    artist: "Gloria Gaynor",
    genre: "Disco",
    isChecked: false,
  },
  {
    id: 14,
    title: "Rapper's Delight",
    artist: "The Sugarhill Gang",
    genre: "Hip Hop",
    isChecked: false,
  },
  {
    id: 15,
    title: "No Woman, No Cry",
    artist: "Bob Marley & The Wailers",
    genre: "Reggae",
    isChecked: false,
  },
  {
    id: 16,
    title: "God Only Knows",
    artist: "The Beach Boys",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 17,
    title: "What a Wonderful World",
    artist: "Louis Armstrong",
    genre: "Jazz",
    isChecked: false,
  },
  {
    id: 18,
    title: "Hallelujah",
    artist: "Leonard Cohen",
    genre: "Folk",
    isChecked: false,
  },
  {
    id: 19,
    title: "Crazy",
    artist: "Patsy Cline",
    genre: "Country",
    isChecked: false,
  },
  {
    id: 20,
    title: "Hit the Road Jack",
    artist: "Ray Charles",
    genre: "Soul",
    isChecked: false,
  },
  {
    id: 21,
    title: "A Change Is Gonna Come",
    artist: "Sam Cooke",
    genre: "Soul",
    isChecked: false,
  },
  {
    id: 22,
    title: "I Wanna Dance With Somebody (Who Loves Me)",
    artist: "Whitney Houston",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 23,
    title: "Dancing Queen",
    artist: "ABBA",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 24,
    title: "Can't Stop the Feeling! (from Trolls)",
    artist: "Justin Timberlake",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 25,
    title: "Thrift Shop",
    artist: "Macklemore & Ryan Lewis",
    genre: "Hip Hop",
    isChecked: false,
  },
  {
    id: 26,
    title: "Lose Yourself",
    artist: "Eminem",
    genre: "Hip Hop",
    isChecked: false,
  },
  {
    id: 27,
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    genre: "Funk",
    isChecked: false,
  },
  {
    id: 28,
    title: "Happy",
    artist: "Pharrell Williams",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 29,
    title: "Rolling in the Deep",
    artist: "Adele",
    genre: "Soul",
    isChecked: false,
  },
  {
    id: 30,
    title: "Let It Go (from Frozen)",
    artist: "Idina Menzel",
    genre: "Soundtrack",
    isChecked: false,
  },
  {
    id: 31,
    title: "Despacito",
    artist: "Luis Fonsi ft. Daddy Yankee",
    genre: "Reggaeton",
    isChecked: false,
  },
  {
    id: 32,
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 33,
    title: "Don't Stop Believin'",
    artist: "Journey",
    genre: "Rock",
    isChecked: false,
  },
  {
    id: 34,
    title: "Livin' on a Prayer",
    artist: "Bon Jovi",
    genre: "Rock",
    isChecked: false,
  },
  {
    id: 35,
    title: "Another One Bites the Dust",
    artist: "Queen",
    genre: "Rock",
    isChecked: false,
  },
  {
    id: 36,
    title: "You Shook Me All Night Long",
    artist: "AC/DC",
    genre: "Hard Rock",
    isChecked: false,
  },
  {
    id: 37,
    title: "Beat It",
    artist: "Michael Jackson",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 38,
    title: "I Want It That Way",
    artist: "Backstreet Boys",
    genre: "Pop",
    isChecked: false,
  },
  {
    id: 39,
    title: "We Will Rock You",
    artist: "Queen",
    genre: "Rock",
    isChecked: false,
  },
  {
    id: 40,
    title: "Wonderwall",
    artist: "Oasis",
    genre: "Britpop",
    isChecked: false,
  },
];

export const tempPlaylist = [];
